//TODO: Translations, Make sure all classes are present
export const classes = [
    {label : 'Guardian', value : 'guardian', key:1},
    {label : 'Nova', value : 'nova', key:2},
    {label : 'Archer', value : 'archer', key:3},
    {label : 'Ranger', value : 'ranger', key:4},
    {label : 'Corsair', value : 'corsair', key:5},
    {label : 'Witch', value : 'witch', key:6},
    {label : 'Wizard', value : 'wizard', key:7},
    {label : 'Dark Knight', value : 'dark knight', key:8},
    {label : 'Lahn', value : 'lahn', key:9},
    {label : 'Valkyrie', value : 'valkyrie', key:10},
    {label : 'Warrior', value : 'warrior', key:11},
    {label : 'Tamer', value : 'tamer', key:12},
    {label : 'Beserker', value : 'beserker', key:13},
    {label : 'Striker', value : 'striker', key:14},
    {label : 'Mystic', value : 'mystic', key:15},
    {label : 'Shai', value : 'shai', key:16},
    {label : 'Sorceress', value : 'sorceress', key:17},
    {label : 'Maehwa', value : 'maehwa', key:18},
    {label : 'Musa', value : 'musa', key:19},
    {label : 'temp', value : 'temp', key:20},
    {label : 'tempNot', value : 'tempNot', key:21},
];